pyts/visualization/visualization.py

adding plt.show() for quality of life improvements

improvement for visualisation

---

pyts/visualization/visualization.py

adding interpolation option for plot_gasf, plot_gadf, plot_mtf and
plot_recurrance_plots

adding interpolation option

---

README.md
setup.py

* Make the example dataset deterministic
* Use scikit-learn instead of sklearn in the requirements (see https://github.com/scikit-learn/scikit-learn/issues/8215)
* Add missing dependency [future](https://pypi.python.org/pypi/future)

Minor fixes

---

pyts/image/image.py

Great repo! Thanks for making this.

Correct small typo

---

doc/changelog.rst
examples/metrics/plot_dtw.py
examples/metrics/plot_itakura.py
examples/metrics/plot_sakoe_chiba.py
pyts/classification/knn.py
pyts/classification/tests/test_knn.py
pyts/metrics/dtw.py
pyts/metrics/tests/test_dtw.py
pyts/multivariate/transformation/multivariate.py

One of the features of the DTW metric is that it can compare time series of different lengths; which is done in this PR
All `region` methods are updated following the same logic by rescaling to the relative diagonal (n_timestamps_2 / n_timestamps_1).
Here is the updated output of the `plot_dtw` example with x = x[::2]

[WIP] DTW computation for time series with different lengths

---

doc/conf.py
setup.py

This small PR:
* adds a **Related Topics** section in the sidebar of the documentation
* removes `sphinx_rtd_theme` from the documentation dependencies in `setup.py`

Improve doc template

---

pyts/bag_of_words/bow.py
pyts/classification/bossvs.py
pyts/decomposition/ssa.py
pyts/transformation/boss.py
pyts/transformation/weasel.py
pyts/utils/utils.py

This small PR adds a numba-njitted version of [pyts.utils.windowed_view](https://pyts.readthedocs.io/en/latest/generated/pyts.utils.windowed_view.html#pyts.utils.windowed_view). This version is now used in other submodules.

Numba version of windowed_view

---

doc/conf.py
doc/scikit_learn_compatibility.rst
examples/approximation/plot_dft.py
examples/approximation/plot_mcb.py
examples/approximation/plot_paa.py
examples/approximation/plot_sax.py
examples/bag_of_words/plot_bow.py
examples/classification/plot_bossvs.py
examples/classification/plot_saxvsm.py
examples/datasets/plot_load_gunpoint.py
examples/datasets/plot_make_cbf.py
examples/decomposition/plot_ssa.py
examples/image/plot_gaf.py
examples/image/plot_mtf.py
examples/image/plot_rp.py
examples/metrics/plot_dtw.py
examples/metrics/plot_itakura.py
examples/metrics/plot_sakoe_chiba.py
examples/multivariate/plot_joint_rp.py
examples/multivariate/plot_weasel_muse.py
examples/plot_ts.py
examples/preprocessing/plot_imputer.py
examples/preprocessing/plot_scalers.py
examples/preprocessing/plot_transformers.py
examples/transformation/plot_boss.py
examples/transformation/plot_shapelet_transform.py
examples/transformation/plot_weasel.py
pyts/metrics/dtw.py
pyts/multivariate/utils/utils.py

This PR updates most of the examples in the `examples` folder:
* better docstring explaining what each algorithm does
* better rendering for several figures.

Update examples in examples folder

---

doc/index.rst
doc/install.rst
doc/reproducibility.rst

This PR adds a `Reproducibility` page in the documentation summarizing the results published on the [pyts-repro](https://github.com/johannfaouzi/pyts-repro) repository.

Reproducibility

---

README.md
azure-pipelines.yml
doc/install.rst
pyts/transformation/shapelet_transform.py
pyts/transformation/tests/test_shapelet_transform.py
pyts/transformation/weasel.py
pyts/utils/utils.py
requirements.txt
setup.py

First set up for Azure Pipelines. YAML file needs changing.

Set up CI with Azure Pipelines

---

doc/reproducibility.rst
pyts/__init__.py

This PR is for the release of version 0.10.0. The *Reproducibility* page in the documentation has been updated with the results of this version.

Release of version 0.10.0

---

README.md
doc/api.rst
doc/modules/transformation.rst
examples/transformation/plot_rocket.py
pyts/transformation/__init__.py
pyts/transformation/rocket.py
pyts/transformation/tests/test_rocket.py

This PR adds the ROCKET algorithm:
* Functions and main class in `pyts/transformation/rocket.py`
* Tests in `pyts/transformation/tests/test_rocket.py`
* Class added in `docs/api.rst`
* Algorithm added in `docs/modules/transformation.rst`
* Example added in `examples/transformation/plot_rocket.py`

Add ROCKET transformer

---

doc/api.rst
doc/modules/bag_of_words.rst
examples/bag_of_words/plot_word_extractor.py
pyts/bag_of_words/__init__.py
pyts/bag_of_words/bow.py
pyts/bag_of_words/tests/test_bow.py
setup.cfg

This PR readds the previous `BagOfWords` algorithm as `WordExtractor`. A warning is raised in `BagOfWords` to warn users about this change.

Readd previous BagOfWords as WordExtractor

---

README.md
doc/citation.rst
doc/index.rst

This small PR adds a citation section in the README, updates the citation page in the documentation and adds this page in the TOC.

Add citation in README and documentation

---

doc/api.rst
doc/modules/classification.rst
examples/classification/plot_time_series_forest.py
pyts/__init__.py
pyts/classification/__init__.py
pyts/classification/tests/test_time_series_forest.py
pyts/classification/time_series_forest.py

This PR adds the Time Series Forest algorithm in the `pyts.classification` module.

Add Time Series Forest algorithm

---

.github/workflows/publish_pypi.yml

This PR adds a workflow to automatically publish to PyPI for any release.

Add workflow to publish to PyPI on release

---

doc/pytsdtwdoc.py
examples/approximation/plot_mcb.py
pyts/approximation/paa.py
pyts/classification/learning_shapelets.py
pyts/classification/time_series_forest.py
pyts/datasets/ucr.py
pyts/datasets/uea.py
pyts/transformation/shapelet_transform.py

This pull request updates some code to comply with changes in more recent versions of some dependencies (scipy, scikit-learn).

Update code to comply with more recent versions of dependencies

---

doc/api.rst
doc/modules/classification.rst
examples/classification/plot_tsbf.py
pyts/classification/__init__.py
pyts/classification/tests/test_tsbf.py
pyts/classification/tsbf.py

This PR adds the Time Series Bag-of-Features (TSBF) classification algorithm

Add TSBF algorithm

---

doc/reproducibility.rst
pyts/__init__.py

This PR is the last one before the release of version 0.12.0:
* The version number is updated.
* The `Reproducibility` page is updated.

Release 0.12.0

---

examples/clustering/README.txt
examples/clustering/plot_dtw_boss.py
examples/decomposition/README.txt
pyts/datasets/make.py
pyts/datasets/tests/test_make.py
pyts/multivariate/transformation/weasel_muse.py

Hello,
because pyts comes with all the necessary requirements for time series clustering, I set up an example regarding different metrics in this context. Even though pyts focuses on classification, I think a concrete example of using BOSS in an unsupervised way is quite useful. What do you think?
The example refers to the original BOSS paper. Since a slightly different form of the data set was used there, I shifted each time series in a second attempt.

Add clustering example and modify CBF dataset function

---

azure-pipelines.yml

This PR tries to solve the issue of Codecov not being included anymore in the continuous integration.

Fix Codecov being missing in the CI
